package show.trom.mod.init;

import net.minecraft.world.food.FoodProperties;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Rarity;
import net.minecraftforge.common.ForgeSpawnEggItem;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;
import show.trom.mod.TromMod;
import show.trom.mod.item.*;

public class TromItem {
    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, TromMod.MOD_ID);
    public static final RegistryObject<Item> DEEPSLATE_WITH_PURPLE_CRYSTAL_SHARD = ITEMS.register("deepslate_with_purple_crystal_shard", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> PURPLE_CRYSTAL_SHARD = ITEMS.register("purple_crystal_shard", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> PURPLE_CRYSTAL_SWORD = ITEMS.register("purple_crystal_sword", PurpleCrystalSword::new);
    public static final RegistryObject<Item> PURPLE_CRYSTAL_HAMMER = ITEMS.register("purple_crystal_hammer", PurpleCrystalHammer::new);
    public static final RegistryObject<Item> COPPER_HELMET = ITEMS.register("copper_helmet", CopperArmor.Helmet::new);
    public static final RegistryObject<Item> COPPER_CHESTPLATE = ITEMS.register("copper_chestplate", CopperArmor.Chestplate::new);
    public static final RegistryObject<Item> COPPER_LEGGINGS = ITEMS.register("copper_leggings", CopperArmor.Leggings::new);
    public static final RegistryObject<Item> COPPER_BOOTS = ITEMS.register("copper_boots", CopperArmor.Boots::new);
    public static final RegistryObject<Item> ROSE_GOLD_INGOT = ITEMS.register("rose_gold_ingot", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> ROSE_GOLD_CROWN = ITEMS.register("rose_gold_crown", RoseGoldArmor.Helmet::new);
    public static final RegistryObject<Item> ROSE_GOLD_CHESTPLATE = ITEMS.register("rose_gold_chestplate", RoseGoldArmor.Chestplate::new);
    public static final RegistryObject<Item> ROSE_GOLD_LEGGINGS = ITEMS.register("rose_gold_leggings", RoseGoldArmor.Leggings::new);
    public static final RegistryObject<Item> ROSE_GOLD_BOOTS = ITEMS.register("rose_gold_boots", RoseGoldArmor.Boots::new);
    public static final RegistryObject<Item> ROSE_GOLD_SWORD = ITEMS.register("rose_gold_sword", RoseGoldSword::new);
    public static final RegistryObject<Item> ROSE_GOLD_PICKAXE = ITEMS.register("rose_gold_pickaxe", RoseGoldPickaxe::new);
    public static final RegistryObject<Item> ROSE_GOLD_AXE = ITEMS.register("rose_gold_axe", RoseGoldAxe::new);
    public static final RegistryObject<Item> ROSE_GOLD_HOE = ITEMS.register("rose_gold_hoe", RoseGoldHoe::new);
    public static final RegistryObject<Item> ROSE_GOLD_SHOVEL = ITEMS.register("rose_gold_shovel", RoseGoldShovel::new);
    public static final RegistryObject<Item> ROSE_GOLD_NUGGET = ITEMS.register("rose_gold_nugget", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> COPPER_GEAR = ITEMS.register("copper_gear", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> COPPER_NUGGET = ITEMS.register("copper_nugget", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> STEEL_PIPE = ITEMS.register("steel_pipe", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> HOLY_STEEL_PIPE = ITEMS.register("holy_steel_pipe", () -> new Item(new Item.Properties().stacksTo(16).rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> STEEL_INGOT = ITEMS.register("steel_ingot", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> STEEL_HELMET = ITEMS.register("steel_helmet", SteelArmor.Helmet::new);
    public static final RegistryObject<Item> STEEL_CHESTPLATE = ITEMS.register("steel_chestplate", SteelArmor.Chestplate::new);
    public static final RegistryObject<Item> STEEL_LEGGINGS = ITEMS.register("steel_leggings", SteelArmor.Leggings::new);
    public static final RegistryObject<Item> STEEL_BOOTS = ITEMS.register("steel_boots", SteelArmor.Boots::new);
    public static final RegistryObject<Item> STEEL_SWORD = ITEMS.register("steel_sword", SteelSword::new);
    public static final RegistryObject<Item> STEEL_PICKAXE = ITEMS.register("steel_pickaxe", SteelPickaxe::new);
    public static final RegistryObject<Item> STEEL_AXE = ITEMS.register("steel_axe", SteelAxe::new);
    public static final RegistryObject<Item> STEEL_SHOVEL = ITEMS.register("steel_shovel", SteelShovel::new);
    public static final RegistryObject<Item> STEEL_HOE = ITEMS.register("steel_hoe", SteelHoe::new);
    public static final RegistryObject<Item> CELESTITE_SWORD = ITEMS.register("celestite_sword", CelestiteSword::new);
    public static final RegistryObject<Item> CELESTITE_PICKAXE = ITEMS.register("celestite_pickaxe", CelestitePickaxe::new);
    public static final RegistryObject<Item> CELESTITE_AXE = ITEMS.register("celestite_axe", CelestiteAxe::new);
    public static final RegistryObject<Item> CELESTITE_HOE = ITEMS.register("celestite_hoe", CelestiteHoe::new);
    public static final RegistryObject<Item> CELESTITE_SHOVEL = ITEMS.register("celestite_shovel", CelestiteShovel::new);
    public static final RegistryObject<Item> STEEL_NUGGET = ITEMS.register("steel_nugget", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> STEEL_PLATE = ITEMS.register("steel_plate", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> STEEL_DUST = ITEMS.register("steel_dust", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> ROSE_GOLD_DUST = ITEMS.register("rose_gold_dust", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> KING_OF_THE_CRYSTAL_SPAWN_EGG = ITEMS.register("king_of_the_crystal_spawn_egg", () -> new ForgeSpawnEggItem(TromEntities.KING_OF_THE_CRYSTAL, 99999999, 99999999, new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> ROCK_CHEESE = ITEMS.register("rock_cheese", () -> new Item(new Item.Properties().food((new FoodProperties.Builder()).nutrition(6).saturationMod(0.6f).alwaysEat().build())));
    public static final RegistryObject<Item> MINERAL_CHEESE = ITEMS.register("mineral_cheese", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON).food((new FoodProperties.Builder()).nutrition(12).saturationMod(1.5f).alwaysEat().build())));
    public static final RegistryObject<Item> CRYSTAL_ZOMBIE_SPAWN_EGG = ITEMS.register("crystal_zombie_spawn_egg", () -> new ForgeSpawnEggItem(TromEntities.CRYSTAL_ZOMBIE, -13421773, -6814312, new Item.Properties()));
    public static final RegistryObject<Item> PURPLE_CRYSTAL_BRICK_SPAWN_EGG = ITEMS.register("purple_crystal_brick_spawn_egg", () -> new ForgeSpawnEggItem(TromEntities.PURPLE_CRYSTAL_BRICK, -10790053, -2150689, new Item.Properties()));
    public static final RegistryObject<Item> CRYSTAL_SKELETON_SPAWN_EGG = ITEMS.register("crystal_skeleton_spawn_egg", () -> new ForgeSpawnEggItem(TromEntities.CRYSTAL_SKELETON, -12171706, -5633366, new Item.Properties()));
    public static final RegistryObject<Item> CRYSTAL_ILLAGER_SPAWN_EGG = ITEMS.register("crystal_illager_spawn_egg", () -> new ForgeSpawnEggItem(TromEntities.CRYSTAL_ILLAGER, -12171706, -5633366, new Item.Properties()));
    public static final RegistryObject<Item> JIN_S_FEATHER = ITEMS.register("jin_s_feather", () -> new Item(new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> CELESTITE_CRYSTAL = ITEMS.register("celestite_crystal", () -> new Item(new Item.Properties()));
    public static final RegistryObject<Item> CELESTITE_HELMET = ITEMS.register("celestite_helmet", CelestiteArmor.Helmet::new);
    public static final RegistryObject<Item> CELESTITE_CHESTPLATE = ITEMS.register("celestite_chestplate", CelestiteArmor.Chestplate::new);
    public static final RegistryObject<Item> CELESTITE_LEGGINGS = ITEMS.register("celestite_leggings", CelestiteArmor.Leggings::new);
    public static final RegistryObject<Item> CELESTITE_BOOTS = ITEMS.register("celestite_boots", CelestiteArmor.Boots::new);
    public static final RegistryObject<Item> CRYSTAL_STAFF = ITEMS.register("crystal_staff", CrystalStaff::new);
}